name: youtube_quality_player
description: A Flutter YouTube player package that supports multiple video qualities, multi speeds, and more.
version: 1.1.3
#author: mayar aboumahmood <abmayar208@gmail.com>
homepage: https://github.com/MayarAboumahmood/youtube_quality_player.git

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_lints: ^6.0.0
  youtube_explode_dart: ^2.5.2
  media_kit_video:  ^1.3.0
  media_kit: ^1.2.0
  media_kit_libs_video: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

#flutter:

# assets:
#   - images/a_dot_burr.jpeg

